In [10]:
import numpy as np
from ClassNeuronaLineal import NeuronaLineal

# Datos de entrada (tres dígitos binarios) y sus correspondientes valores decimales
X = np.array([[0, 0, 0],
              [0, 0, 1],
              [0, 1, 0],
              [0, 1, 1],
              [1, 0, 0],
              [1, 0, 1],
              [1, 1, 0],
              [1, 1, 1]])

# Salidas correspondientes (valores decimales)
T = np.array([0, 1, 2, 3, 4, 5, 6, 7])

alfa = 0.05
MAX_ITE = 200
CotaError = 10e-03

modelo = NeuronaLineal(alpha=alfa, n_iter=MAX_ITE, cotaE=CotaError)
modelo.fit(X, T)
modelo.w_

array([3.89542629, 1.90334037, 0.91193392])

In [11]:
modelo.n_iter

200

In [12]:
X_bias = np.c_[np.ones(X.shape[0]), X]
X_bias

array([[1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [13]:
T = np.array([0, 1, 2, 3, 4, 5, 6, 7])

alfa = 0.05
MAX_ITE = 200
CotaError = 10e-03

modelo = NeuronaLineal(alpha=alfa, n_iter=MAX_ITE, cotaE=CotaError)
modelo.fit(X_bias, T)
modelo.w_

array([0.36204048, 3.90242209, 1.92121328, 0.94081433])

In [14]:
modelo.n_iter

200